export const ERRORS = "ERRORS"
export const UPDATE_FIAT_DEPOSIT = "UPDATE_FIAT_DEPOSIT"
export const CLEAR_RESPONSE = "CLEAR_RESPONSE"
export const UPDATE_FIAT_DEPOSIT_SUCCESS = "UPDATE_FIAT_DEPOSIT_SUCCESS"



