export const ERRORS = "ERRORS";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";

export const CREATE_ASSETS_CURRENCY_REQUEST = "CREATE_ASSETS_CURRENCY_REQUEST";
export const CREATE_ASSETS_CURRENCY_SUCCESS = "CREATE_ASSETS_CURRENCY_SUCCESS";
export const CREATE_ASSETS_CURRENCY_FAILURE = "CREATE_ASSETS_CURRENCY_FAILURE";

export const UPDATE_ASSETS_CURRENCY_REQUEST = "UPDATE_ASSETS_CURRENCY_REQUEST";
export const UPDATE_ASSETS_CURRENCY_SUCCESS = "UPDATE_ASSETS_CURRENCY_SUCCESS";
export const UPDATE_ASSETS_CURRENCY_FAILURE = "UPDATE_ASSETS_CURRENCY_FAILURE";

export const REMOVE_ASSETS_CURRENCY_REQUEST = "REMOVE_ASSETS_CURRENCY_REQUEST";
export const REMOVE_ASSETS_CURRENCY_SUCCESS = "REMOVE_ASSETS_CURRENCY_SUCCESS";
export const REMOVE_ASSETS_CURRENCY_FAILURE = "REMOVE_ASSETS_CURRENCY_FAILURE";



export const UPDATE_ASSETS_CURRENCY_ADV_REQUEST = "UPDATE_ASSETS_CURRENCY_ADV_REQUEST";
export const UPDATE_ASSETS_CURRENCY_ADV_SUCCESS = "UPDATE_ASSETS_CURRENCY_ADV_SUCCESS";
export const UPDATE_ASSETS_CURRENCY_ADV_FAILURE = "UPDATE_ASSETS_CURRENCY_ADV_FAILURE";

export const CREATE_ASSETS_CURRENCY_ADV_REQUEST = "CREATE_ASSETS_CURRENCY_ADV_REQUEST";
export const CREATE_ASSETS_CURRENCY_ADV_SUCCESS = "CREATE_ASSETS_CURRENCY_ADV_SUCCESS";
export const CREATE_ASSETS_CURRENCY_ADV_FAILURE = "CREATE_ASSETS_CURRENCY_ADV_FAILURE";

export const REMOVE_ASSETS_CURRENCY_ADV_REQUEST = "REMOVE_ASSETS_CURRENCY_ADV_REQUEST";
export const REMOVE_ASSETS_CURRENCY_ADV_SUCCESS = "REMOVE_ASSETS_CURRENCY_ADV_SUCCESS";
export const REMOVE_ASSETS_CURRENCY_ADV_FAILURE = "REMOVE_ASSETS_CURRENCY_ADV_FAILURE";

	
