

export const ADMIN_WALLET_ADDRESS_DELETE = "ADMIN_WALLET_ADDRESS_DELETE";
export const ADMIN_WALLET_ADDRESS_DELETE_FAILURE =
	"ADMIN_WALLET_ADDRESS_DELETE_FAILURE";
export const ADMIN_WALLET_ADDRESS_DELETE_SUCCESS =
	"ADMIN_WALLET_ADDRESS_DELETE_SUCCESS";

export const ADMIN_WALLET_ADDRESS_UPDATE = "ADMIN_WALLET_ADDRESS_UPDATE";
export const ADMIN_WALLET_ADDRESS_UPDATE_FAILURE =
	"ADMIN_WALLET_ADDRESS_UPDATE_FAILURE";
export const ADMIN_WALLET_ADDRESS_UPDATE_SUCCESS =
	"ADMIN_WALLET_ADDRESS_UPDATE_SUCCESS";

export const ADMIN_WALLET_ADDRESS_CREATE = "ADMIN_WALLET_ADDRESS_CREATE";
export const ADMIN_WALLET_ADDRESS_CREATE_FAILURE =
	"ADMIN_WALLET_ADDRESS_CREATE_FAILURE";
export const ADMIN_WALLET_ADDRESS_CREATE_SUCCESS =
	"ADMIN_WALLET_ADDRESS_CREATE_SUCCESS";

export const CLEAR_RESPONSE = "CLEAR_RESPONSE";
export const ERRORS = "ERRORS";
