export const ERRORS = "ERRORS";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";

export const CREATE_ARTICLE_REQUEST = "CREATE_ARTICLE_REQUEST";
export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
export const CREATE_ARTICLE_FAILURE = "CREATE_ARTICLE_FAILURE";

export const UPDATE_ARTICLE_REQUEST = "UPDATE_ARTICLE_REQUEST";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_FAILURE = "UPDATE_ARTICLE_FAILURE";

export const REMOVE_ARTICLE_REQUEST = "REMOVE_ARTICLE_REQUEST";
export const REMOVE_ARTICLE_SUCCESS = "REMOVE_ARTICLE_SUCCESS";
export const REMOVE_ARTICLE_FAILURE = "REMOVE_ARTICLE_FAILURE";

export const FEATURE_ARTICLE_REQUEST = "FEATURE_ARTICLE_REQUEST";
export const FEATURE_ARTICLE_SUCCESS = "FEATURE_ARTICLE_SUCCESS";
export const FEATURE_ARTICLE_FAILURE = "FEATURE_ARTICLE_FAILURE";

export const TOGGLE_ARTICLE_SUCCESS = "TOGGLE_ARTICLE_SUCCESS";
export const TOGGLE_ARTICLE_REQUEST = "TOGGLE_ARTICLE_REQUEST";
export const TOGGLE_ARTICLE_FAILURE = "TOGGLE_ARTICLE_FAILURE";

export const TOGGLE_ARTICLE_TAG_SUCCESS = "TOGGLE_ARTICLE_TAG_SUCCESS";
export const TOGGLE_ARTICLE_TAG_REQUEST = "TOGGLE_ARTICLE_TAG_REQUEST";
export const TOGGLE_ARTICLE_TAG_FAILURE = "TOGGLE_ARTICLE_TAG_FAILURE";

export const TOGGLE_ARTICLE_CATEGORY_SUCCESS =
	"TOGGLE_ARTICLE_CATEGORY_SUCCESS";
export const TOGGLE_ARTICLE_CATEGORY_REQUEST =
	"TOGGLE_ARTICLE_CATEGORY_REQUEST";
export const TOGGLE_ARTICLE_CATEGORY_FAILURE =
	"TOGGLE_ARTICLE_CATEGORY_FAILURE";

export const ARTICLE_TAG_REQUEST = "ARTICLE_TAG_REQUEST";
export const ARTICLE_TAG_FAILURE = "ARTICLE_TAG_FAILURE";
export const ARTICLE_TAG_SUCCESS = "ARTICLE_TAG_SUCCESS";

export const CREATE_ARTICLE_TAG_REQUEST = "CREATE_ARTICLE_TAG_REQUEST";
export const CREATE_ARTICLE_TAG_SUCCESS = "CREATE_ARTICLE_TAG_SUCCESS";
export const CREATE_ARTICLE_TAG_FAILURE = "CREATE_ARTICLE_TAG_FAILURE";

export const UPDATE_ARTICLE_TAG_REQUEST = "UPDATE_ARTICLE_TAG_REQUEST";
export const UPDATE_ARTICLE_TAG_SUCCESS = "UPDATE_ARTICLE_TAG_SUCCESS";
export const UPDATE_ARTICLE_TAG_FAILURE = "UPDATE_ARTICLE_TAG_FAILURE";

export const REMOVE_ARTICLE_TAG_REQUEST = "REMOVE_ARTICLE_TAG_REQUEST";
export const REMOVE_ARTICLE_TAG_SUCCESS = "REMOVE_ARTICLE_TAG_SUCCESS";
export const REMOVE_ARTICLE_TAG_FAILURE = "REMOVE_ARTICLE_TAG_FAILURE";

export const ARTICLE_CATEGORY_REQUEST = "ARTICLE_CATEGORY_REQUEST";
export const ARTICLE_CATEGORY_FAILURE = "ARTICLE_CATEGORY_FAILURE";
export const ARTICLE_CATEGORY_SUCCESS = "ARTICLE_CATEGORY_SUCCESS";

export const CREATE_ARTICLE_CATEGORY_REQUEST =
	"CREATE_ARTICLE_CATEGORY_REQUEST";
export const CREATE_ARTICLE_CATEGORY_SUCCESS =
	"CREATE_ARTICLE_CATEGORY_SUCCESS";
export const CREATE_ARTICLE_CATEGORY_FAILURE =
	"CREATE_ARTICLE_CATEGORY_FAILURE";

export const UPDATE_ARTICLE_CATEGORY_REQUEST =
	"UPDATE_ARTICLE_CATEGORY_REQUEST";
export const UPDATE_ARTICLE_CATEGORY_SUCCESS =
	"UPDATE_ARTICLE_CATEGORY_SUCCESS";
export const UPDATE_ARTICLE_CATEGORY_FAILURE =
	"UPDATE_ARTICLE_CATEGORY_FAILURE";

export const REMOVE_ARTICLE_CATEGORY_REQUEST =
	"REMOVE_ARTICLE_CATEGORY_REQUEST";
export const REMOVE_ARTICLE_CATEGORY_SUCCESS =
	"REMOVE_ARTICLE_CATEGORY_SUCCESS";
export const REMOVE_ARTICLE_CATEGORY_FAILURE =
	"REMOVE_ARTICLE_CATEGORY_FAILURE";
