export const ERRORS = "ERRORS";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";

export const CREATE_TRADING_LEVEL_REQUEST = "CREATE_TRADING_LEVEL_REQUEST";
export const CREATE_TRADING_LEVEL_SUCCESS = "CREATE_TRADING_LEVEL_SUCCESS";
export const CREATE_TRADING_LEVEL_FAILURE = "CREATE_TRADING_LEVEL_FAILURE";

export const UPDATE_TRADING_LEVEL_REQUEST = "UPDATE_TRADING_LEVEL_REQUEST";
export const UPDATE_TRADING_LEVEL_SUCCESS = "UPDATE_TRADING_LEVEL_SUCCESS";
export const UPDATE_TRADING_LEVEL_FAILURE = "UPDATE_TRADING_LEVEL_FAILURE";

export const REMOVE_TRADING_LEVEL_REQUEST = "REMOVE_TRADING_LEVEL_REQUEST";
export const REMOVE_TRADING_LEVEL_SUCCESS = "REMOVE_TRADING_LEVEL_SUCCESS";
export const REMOVE_TRADING_LEVEL_FAILURE = "REMOVE_TRADING_LEVEL_FAILURE";
