export const ANNOUNCEMENT_DELETE = "ANNOUNCEMENT_DELETE";
export const ANNOUNCEMENT_DELETE_FAILURE = "ANNOUNCEMENT_DELETE_FAILURE";
export const ANNOUNCEMENT_DELETE_SUCCESS = "ANNOUNCEMENT_DELETE_SUCCESS";

export const ANNOUNCEMENT_UPDATE = "ANNOUNCEMENT_UPDATE";
export const ANNOUNCEMENT_UPDATE_FAILURE = "ANNOUNCEMENT_UPDATE_FAILURE";
export const ANNOUNCEMENT_UPDATE_SUCCESS = "ANNOUNCEMENT_UPDATE_SUCCESS";

export const ANNOUNCEMENT_CREATE = "ANNOUNCEMENT_CREATE";
export const ANNOUNCEMENT_CREATE_FAILURE = "ANNOUNCEMENT_CREATE_FAILURE";
export const ANNOUNCEMENT_CREATE_SUCCESS = "ANNOUNCEMENT_CREATE_SUCCESS";

export const CLEAR_RESPONSE = "CLEAR_RESPONSE";

export const ERRORS = "ERRORS";
