export const ERRORS = "ERRORS";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";

export const CREATE_TRADING_MAINTENANCE_REQUEST =
	"CREATE_TRADING_MAINTENANCE_REQUEST";
export const CREATE_TRADING_MAINTENANCE_SUCCESS =
	"CREATE_TRADING_MAINTENANCE_SUCCESS";
export const CREATE_TRADING_MAINTENANCE_FAILURE =
	"CREATE_TRADING_MAINTENANCE_FAILURE";

export const UPDATE_TRADING_MAINTENANCE_REQUEST =
	"UPDATE_TRADING_MAINTENANCE_REQUEST";
export const UPDATE_TRADING_MAINTENANCE_SUCCESS =
	"UPDATE_TRADING_MAINTENANCE_SUCCESS";
export const UPDATE_TRADING_MAINTENANCE_FAILURE =
	"UPDATE_TRADING_MAINTENANCE_FAILURE";

export const TOGGLE_TRADING_MAINTENANCE_REQUEST =
	"TOGGLE_TRADING_MAINTENANCE_REQUEST";
export const TOGGLE_TRADING_MAINTENANCE_SUCCESS =
	"TOGGLE_TRADING_MAINTENANCE_SUCCESS";
export const TOGGLE_TRADING_MAINTENANCE_FAILURE =
	"TOGGLE_TRADING_MAINTENANCE_FAILURE";

export const REMOVE_TRADING_MAINTENANCE_REQUEST =
	"REMOVE_TRADING_MAINTENANCE_REQUEST";
export const REMOVE_TRADING_MAINTENANCE_SUCCESS =
	"REMOVE_TRADING_MAINTENANCE_SUCCESS";
export const REMOVE_TRADING_MAINTENANCE_FAILURE =
	"REMOVE_TRADING_MAINTENANCE_FAILURE";

export const CREATE_WALLET_MAINTENANCE_REQUEST =
	"CREATE_WALLET_MAINTENANCE_REQUEST";
export const CREATE_WALLET_MAINTENANCE_SUCCESS =
	"CREATE_WALLET_MAINTENANCE_SUCCESS";
export const CREATE_WALLET_MAINTENANCE_FAILURE =
	"CREATE_WALLET_MAINTENANCE_FAILURE";

export const TOGGLE_WALLET_MAINTENANCE_REQUEST =
	"TOGGLE_WALLET_MAINTENANCE_REQUEST";
export const TOGGLE_WALLET_MAINTENANCE_SUCCESS =
	"TOGGLE_WALLET_MAINTENANCE_SUCCESS";
export const TOGGLE_WALLET_MAINTENANCE_FAILURE =
	"TOGGLE_WALLET_MAINTENANCE_FAILURE";

export const UPDATE_WALLET_MAINTENANCE_REQUEST =
	"UPDATE_WALLET_MAINTENANCE_REQUEST";
export const UPDATE_WALLET_MAINTENANCE_SUCCESS =
	"UPDATE_WALLET_MAINTENANCE_SUCCESS";
export const UPDATE_WALLET_MAINTENANCE_FAILURE =
	"UPDATE_WALLET_MAINTENANCE_FAILURE";

export const REMOVE_WALLET_MAINTENANCE_REQUEST =
	"REMOVE_WALLET_MAINTENANCE_REQUEST";
export const REMOVE_WALLET_MAINTENANCE_SUCCESS =
	"REMOVE_WALLET_MAINTENANCE_SUCCESS";
export const REMOVE_WALLET_MAINTENANCE_FAILURE =
	"REMOVE_WALLET_MAINTENANCE_FAILURE";


export const TOGGLE_MAINTENANCE_REQUEST = "TOGGLE_MAINTENANCE_REQUEST";
export const TOGGLE_MAINTENANCE_SUCCESS = "TOGGLE_MAINTENANCE_SUCCESS";
export const TOGGLE_MAINTENANCE_FAILURE = "TOGGLE_MAINTENANCE_FAILURE";
