export const ERRORS = "ERRORS";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";
export const UPDATE_FIAT_WITHDRAWAL = "UPDATE_FIAT_WITHDRAWAL";
export const UPDATE_FIAT_WITHDRAWAL_SUCCESS = "UPDATE_FIAT_WITHDRAWAL_SUCCESS";
export const UPDATE_CRYPTO_WITHDRAWAL = "UPDATE_CRYPTO_WITHDRAWAL";
export const UPDATE_CRYPTO_WITHDRAWAL_SUCCESS =
	"UPDATE_CRYPTO_WITHDRAWAL_SUCCESS";
